<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<Optimize>false</Optimize>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentAssertions" Version="4.19.4" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
		<PackageReference Include="NUnit" Version="3.9.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="3.9.0" />
		<PackageReference Include ="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SamplesServiceModelGenerator\SamplesServiceModelGenerator.csproj" />
	</ItemGroup>

</Project>
